# Generated by Django 4.1.7 on 2023-04-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2bApp', '0003_rename_company_additional_business_secont_companyinfo_company_additional_business_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='Franchise_company_banner_first',
            field=models.ImageField(blank=True, null=True, upload_to='Companysubbanner/franchies/banner'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='Franchise_company_banner_second',
            field=models.ImageField(blank=True, null=True, upload_to='Companysubbanner/franchies/banner'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='Franchise_company_banner_third',
            field=models.ImageField(blank=True, null=True, upload_to='Companysubbanner/franchies/banner'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='Company_banner',
            field=models.ImageField(blank=True, null=True, upload_to='Companybanner'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='Company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='companylogo'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='Company_subbanner',
            field=models.ImageField(blank=True, null=True, upload_to='Companysubbanner'),
        ),
    ]
