# Generated by Django 4.1.7 on 2023-04-27 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('B2bApp', '0005_companyinfo_company_brochure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='Company_additional_business_first',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='Company_additional_business_forth',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='Company_additional_business_second',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='Company_additional_business_third',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='Franchise_company_banner_second',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='Franchise_company_banner_third',
        ),
        migrations.CreateModel(
            name='Franchise_company_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='Companysubbanner/franchies/banner')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B2bApp.companyinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Company_Additional_Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B2bApp.companyinfo')),
            ],
        ),
    ]
