# Generated by Django 4.1.7 on 2023-04-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2bApp', '0006_remove_companyinfo_company_additional_business_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='Company_gts_no',
            field=models.CharField(blank=True, default='********', max_length=100, null=True),
        ),
    ]
