# Generated by Django 4.1.7 on 2023-04-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2bApp', '0007_alter_companyinfo_company_gts_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='Franchise_company_banner_first',
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='Company_gts_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
