# Generated by Django 4.1.7 on 2023-04-27 09:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B2bApp', '0008_remove_companyinfo_franchise_company_banner_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='Company_about',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='Company_description',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
