# Generated by Django 4.1.3 on 2023-04-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("B2bApp", "0009_alter_companyinfo_company_about_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyinfo",
            name="Company_url",
        ),
    ]
