# Generated by Django 4.1.3 on 2023-05-05 05:49

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("B2bApp", "0014_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="Company_color1",
            field=colorfield.fields.ColorField(
                default="#f8f9fa", image_field=None, max_length=18, samples=None
            ),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="Company_color2",
            field=colorfield.fields.ColorField(
                default="##dc3545", image_field=None, max_length=18, samples=None
            ),
        ),
    ]
