# Generated by Django 4.1.7 on 2023-04-24 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FranchiseApp', '0002_edmundproducts_medfenseproducts_mitsproducts_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RonishProducts',
        ),
    ]
