# Generated by Django 4.1.7 on 2023-04-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FranchiseApp', '0004_ronishproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RonishProducts',
        ),
        migrations.DeleteModel(
            name='ServoProducts',
        ),
    ]
