# Generated by Django 4.1.7 on 2023-04-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FranchiseApp', '0008_edmundproducts_logo_edmundproducts_pdf_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
