# Generated by Django 4.1.7 on 2023-04-27 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('B2bApp', '0005_companyinfo_company_brochure'),
        ('FranchiseApp', '0009_delete_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitsproducts',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='B2bApp.companyinfo'),
            preserve_default=False,
        ),
    ]
