# Generated by Django 4.1.7 on 2023-04-27 09:47

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FranchiseApp', '0012_delete_edmundproducts_delete_medfenseproducts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdmundProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
                ('pro_image', models.ImageField(upload_to='edmundproductimage')),
                ('description', models.TextField(max_length=500)),
                ('packing', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedFenseProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
                ('pro_image', models.ImageField(upload_to='medfensseproductimage')),
                ('description', models.TextField(max_length=500)),
                ('packing', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RapidProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
                ('pro_image', models.ImageField(upload_to='rapidproductimage')),
                ('description', models.TextField(max_length=500)),
                ('packing', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RonishProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
                ('pro_image', models.ImageField(upload_to='ronishproductimage')),
                ('description', models.TextField(max_length=500)),
                ('packing', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServoProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
                ('pro_image', models.ImageField(upload_to='servoproductimage')),
                ('description', models.TextField(max_length=500)),
                ('packing', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShineProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
                ('pro_image', models.ImageField(upload_to='shineproductimage')),
                ('description', models.TextField(max_length=500)),
                ('packing', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
