# Generated by Django 4.1.3 on 2023-04-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("B2bApp", "0010_remove_companyinfo_company_url"),
        ("FranchiseApp", "0014_delete_edmundproducts_delete_medfenseproducts_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MitsProducts",
            new_name="Products",
        ),
    ]
